### ISSUE TITLE
Not logging errors

### ISSUE THREAD

**Issue by jazeelkt** [himani93/heimdall#6]
I don't see errors (such as a 400 Bad Request) getting logged. I get logs only for successful requests, that return a 200 status code.

**Comment by himani93** [comment]
I have checked, error messages are not getting logged.

I am working on it.

**Comment by jazeelkt** [comment]
@himani93 I guess the problem is with aborting a request using Abort enum. I think these errors are not getting caught in Heimdall. I did find a workaround by using Response.

So instead of `throw Abort.custom(status: status, message: errorMsg)`, I used `return try Response(status: status, json: errorMsg)`. Now Heimdall is capturing errors too.

**Comment by goelankitt** [comment]
I have found this issue. @himani93 I need you to test this please, I don't have environment setup on my new machine. https://github.com/himani93/heimdall/blob/6_log_errors/Sources/Logger.swift#L38

**Comment by himani93** [comment]
Appending AbortMiddleware() after Heimdall, logs errors too.

**Comment by goelankitt** [comment]
@jazeelkt Hey! Thanks for reporting the issue. It has now been fixed.
